version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: sua-aplicacao
    container_name: app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./:/app  # Mapeia o diretório atual para /app dentro do contêiner
      - ~/.m2:/root/.m2  # Opcional: Cache do Maven para acelerar builds
      - ./target:/app/target
    command: ./mvnw spring-boot:run -Dspring-boot.run.fork=false
    networks:
      - app-network

  db:
    image: postgres:13-alpine
    container_name: db
    environment:
      POSTGRES_DB: meu_banco
      POSTGRES_USER: meu_usuario
      POSTGRES_PASSWORD: minha_senha
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network: